"""Initial migration

Revision ID: 520f40cb4fb9
Revises: 
Create Date: 2025-03-28 18:07:18.731446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520f40cb4fb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_quiz_attempt', ['user_id', 'quiz_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_quiz_attempt', type_='unique')

    # ### end Alembic commands ###
