"""initial migration

Revision ID: a869f2bc3286
Revises: d8b665432852
Create Date: 2025-04-22 19:57:20.517067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a869f2bc3286'
down_revision = 'd8b665432852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
