"""Added quiz relationship to Score model

Revision ID: d8b665432852
Revises: 520f40cb4fb9
Create Date: 2025-03-29 11:47:59.657882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b665432852'
down_revision = '520f40cb4fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_score',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp_attempted', sa.DATETIME(), nullable=False),
    sa.Column('total_scored', sa.INTEGER(), nullable=False),
    sa.Column('total_marks', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date_attempted', sa.DATE(), nullable=False),
    sa.Column('total_questions', sa.INTEGER(), nullable=False),
    sa.Column('attempts', sa.INTEGER(), nullable=False),
    sa.Column('correct_answers', sa.INTEGER(), nullable=False),
    sa.Column('time_taken', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quiz_id', name='unique_user_quiz_attempt')
    )
    # ### end Alembic commands ###
